# -*- coding: utf-8 -*-
"""Arabic_01,26

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2RyHJ6x_IJrjuvlKC6B5gLhp6oN78XR
"""

import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image

print("Libraries imported successfully")

dataset_path = "/content/drive/MyDrive/Arabic_dataset/Arabic/user001"
print(dataset_path)

"""Dataset exploration"""

classes = os.listdir(dataset_path)

print("Number of Classes:", len(classes))
print("Classes:", classes)

class_counts = {}

for character_class in classes:
    class_path = os.path.join(dataset_path, character_class)

    if os.path.isdir(class_path):
        count = len(os.listdir(class_path))
        class_counts[character_class] = count

print("Images in each class:\n")

for character, count in class_counts.items():
    print(character, ":", count)

import os

print(os.listdir(dataset_path))

"""Preprocessing

"""

import cv2
import matplotlib.pyplot as plt
import os

# Select first image
image_file = os.listdir(dataset_path)[0]

# Read image
image_path = os.path.join(dataset_path, image_file)
img = cv2.imread(image_path)

print("Image:", image_file)
print("Shape:", img.shape)

# Display image
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.show()

character_class = image_file.split("_")[1]

print("Character Class:", character_class)

"""Convert to Grayscale"""

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.imshow(gray, cmap='gray')
plt.title("Grayscale Image")
plt.axis('off')
plt.show()

"""Resize"""

resized = cv2.resize(gray, (64, 64))

plt.imshow(resized, cmap='gray')
plt.title("Resized Image")
plt.axis('off')
plt.show()

"""Feature Preparation"""

import cv2
import numpy as np
import os

images = []
labels = []

for image_file in os.listdir(dataset_path):

    image_path = os.path.join(dataset_path, image_file)

    # Extract Arabic character from filename
    # Example: user001_alif_end_034.png → alif
    parts = image_file.split("_")

    if len(parts) >= 2:
        character_class = parts[1]

        img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

        if img is not None:
            # Resize
            img = cv2.resize(img, (64, 64))

            # Flatten image
            images.append(img.flatten())
            labels.append(character_class)

X = np.array(images)
y = np.array(labels)

print("Feature Shape:", X.shape)
print("Label Shape:", y.shape)
print("Classes:", np.unique(y))
print("Number of Classes:", len(np.unique(y)))

"""Train/Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Images:", X_train.shape[0])
print("Testing Images:", X_test.shape[0])

"""Train Multi-Class SVM"""

from sklearn.svm import SVC

model = SVC(
    kernel='rbf',
    C=10,
    gamma='scale'
)

model.fit(X_train, y_train)

print("SVM model trained successfully")

"""Train"""

from sklearn.svm import SVC

model = SVC(
    kernel='rbf',
    C=10,
    gamma='scale'
)

model.fit(X_train, y_train)

"""Predict"""

y_pred = model.predict(X_test)

print("Predicted:", y_pred[:10])
print("Actual:", y_test[:10])

"""Check Accuracy"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 8))
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted Class")
plt.ylabel("Actual Class")
plt.colorbar()
plt.show()

"""Display text img with prediction"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))

for i in range(10):
    plt.subplot(2, 5, i + 1)

    plt.imshow(X_test[i].reshape(64, 64), cmap='gray')
    plt.title(f"Actual: {y_test[i]}\nPredicted: {y_pred[i]}")
    plt.axis('off')

plt.tight_layout()
plt.show()

"""Test with a new/unseen image   or New img Prediction"""

import cv2
import numpy as np
import matplotlib.pyplot as plt


# Path of new image
image_path = "/content/drive/MyDrive/Arabic_dataset/Arabic/user001/user001_ain_begin_032.png"

# Read image in grayscale
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

# Check image
if img is None:
    print("Error: Image not found. Check the image path.")
else:
    # Resize to same size used during training
    img_resized = cv2.resize(img, (64, 64))

    # Flatten image
    img_flattened = img_resized.flatten()

    # Convert to NumPy array
    new_image = np.array([img_flattened])

    # Predict using trained SVM
    prediction = model.predict(new_image)

    # Display prediction
    print("Predicted Arabic Character:", prediction[0])

    # Display image
    plt.figure(figsize=(5, 5))
    plt.imshow(img_resized, cmap="gray")
    plt.title("Predicted: " + str(prediction[0]))
    plt.axis("off")
    plt.show()

"""Classification Report"""

from sklearn.metrics import classification_report

print("Classification Report")
print(classification_report(y_test, y_pred))

"""Final Model Performance"""

from sklearn.metrics import accuracy_score

final_accuracy = accuracy_score(y_test, y_pred)

print("Final Model Accuracy:", final_accuracy)
print("Final Model Accuracy (%):", final_accuracy * 100)

"""Identify Frequently Misclassified Classes"""

from sklearn.metrics import confusion_matrix
import numpy as np

# Get the actual labels present in the test data
labels = np.unique(y_test)

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=labels)

print("Frequently Misclassified Character Pairs")
print("------------------------------------------")

misclassified_pairs = []

for i in range(len(labels)):
    for j in range(len(labels)):

        # Ignore correct predictions
        if i != j and cm[i, j] > 0:

            misclassified_pairs.append(
                (cm[i, j], labels[i], labels[j])
            )

# Sort by highest number of errors
misclassified_pairs.sort(reverse=True)

if len(misclassified_pairs) == 0:
    print("No misclassified classes found.")
else:
    for count, actual, predicted in misclassified_pairs:
        print(
            "Actual:", actual,
            "-> Predicted:", predicted,
            "(", count, "images)"
        )

"""Interpretation of Classification Results"""

from sklearn.metrics import precision_recall_fscore_support
import numpy as np

precision, recall, f1, support = precision_recall_fscore_support(
    y_test,
    y_pred,
    labels=np.unique(y_test),
    zero_division=0
)

print("Classification Results Interpretation")
print("--------------------------------------")

for i, label in enumerate(np.unique(y_test)):
    print(f"\nCharacter Class: {label}")
    print(f"Precision: {precision[i]:.2f}")
    print(f"Recall: {recall[i]:.2f}")
    print(f"F1-Score: {f1[i]:.2f}")

    if f1[i] >= 0.80:
        print("Interpretation: This class is recognized well by the SVM.")
    elif f1[i] >= 0.60:
        print("Interpretation: This class has moderate recognition performance.")
    else:
        print("Interpretation: This class is difficult for the SVM to recognize and is frequently confused with other classes.")